export const SET_SELECTED_FILE = 'SET_SELECTED_FILE';
export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const SET_ORDERS_LOADING = 'SET_ORDERS_LOADING';
export const SET_FILE_LOADING = 'SET_FILE_LOADING';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const GET_FILE_ERROR = 'GET_FILE_ERROR';